#!/bin/perl
use strict;
use warnings;

my ($regex, $output, $filename)=@ARGV;

if(!defined $regex) {
  print "Usage: xgrep regex [output] [filename]\n";
  exit(0);
}

sub quote {
  qq{"@_"};
}

sub parse {
  my $fh=shift;
  my $regex=shift;
  my $output=shift;

  while(<$fh>) {
    if($_=~$regex) {
      if(defined $output) {
        print eval(quote($output));
      } else {
        print;
      }
    }
  }
}

my $fh;
if(-p STDIN) {
  $fh=*STDIN;
  parse($fh, $regex, $output);
} else {
  undef($output) if -e $output;
  for $filename (@ARGV[1..$#ARGV]) {
    if(-e $filename) {
      open($fh, '<', $filename);
      parse($fh, $regex, $output);
      close($fh);
    }
  }
}
